# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

env:
  PROJECT_NAME: fugo-blog-bot
  REGION: asia-northeast1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          # Optional service account key to use for authentication to GCP. This should be the JSON formatted private key which can be exported from the Cloud Console. The value can be raw or base64-encoded.
          credentials: ${{ secrets.GCP_SA_KEY }}
          # Name of the Cloud Function.
          name: ${{ env.PROJECT_NAME }}
          # Description for the Cloud Function.
          description: Twitter bot for fugo blog update notification
          # Project to deploy the function in.
          project_id: ${{ secrets.GCP_PROJECT }}
          # Region to deploy the function in. Defaults to us-central1, if not specified.
          region: ${{ env.REGION }}
          # List of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2.
          env_vars: ${{ secrets.ENV_VARS }}
          # Name of a function (as defined in source code) that will be executed. Defaults to the resource name suffix, if not specified. 
          entry_point: Handler
          # Runtime to use for the function.
          runtime: go113
          # Specifies which action should trigger the function.
          event_trigger_type: google.pubsub.topic.publish
          # Specifies which resource from eventTrigger is observed.
          event_trigger_resource: projects/${{ secrets.GCP_PROJECT }}/topics/${{ env.PROJECT_NAME }}
